package com.jeanbarrossilva.geoperiod

import com.jeanbarrossilva.geoperiod.Series.*

enum class Period(vararg series: Series) {
    QUATERNARY(HOLOCENE, PLEISTOCENE),
    NEOGENE(PLIOCENE, MIOCENE),
    PALEOGENE(OLIGOCENE, EOCENE, PALEOCENE),
    CRETACEOUS(CRETACEOUS_UPPER, CRETACEOUS_LOWER),
    JURASSIC(JURASSIC_UPPER, JURASSIC_MIDDLE, JURASSIC_LOWER),
    TRIASSIC(TRIASSIC_UPPER, TRIASSIC_MIDDLE, TRIASSIC_LOWER),
    PERMIAN(LOPINGIAN, GUADALUPIAN, CISURALIAN),
    CARBONIFEROUS(UPPER_PENNSYLVANIAN, MIDDLE_PENNSYLVANIAN, LOWER_PENNSYLVANIAN, UPPER_MISSISSIPPIAN, MIDDLE_MISSISSIPPIAN, LOWER_MISSISSIPPIAN),
    DEVONIAN(DEVONIAN_UPPER, DEVONIAN_MIDDLE, DEVONIAN_LOWER),
    SILURIAN(PRIDOLI, LUDLOW, WENLOCK, LLANDOVERY),
    ORDOVICIAN(ORDOVICIAN_UPPER, ORDOVICIAN_MIDDLE, ORDOVICIAN_LOWER),
    CAMBRIAN(FURONGIAN, SERIES_3, SERIES_2, TERRENEUVIAN),
    EDIACARAN(EDIACARAN_PERIOD),
    CRYOGENIAN(CRYOGENIAN_PERIOD),
    TONIAN(TONIAN_PERIOD),
    STENIAN(STENIAN_PERIOD),
    ECTASIAN(ECTASIAN_PERIOD),
    CALYMMIAN(CALYMMIAN_PERIOD),
    STATHERIAN(STATHERIAN_PERIOD),
    OROSIRIAN(OROSIRIAN_PERIOD),
    RHYACIAN(RHYACIAN_PERIOD),
    SIDERIAN(SIDERIAN_PERIOD),
    NEOARCHEAN_ERATHEM(Series.NEOARCHEAN_ERATHEM),
    MESOARCHEAN_ERATHEM(Series.MESOARCHEAN_ERATHEM),
    PALEOARCHEAN_ERATHEM(Series.PALEOARCHEAN_ERATHEM),
    EOARCHEAN_ERATHEM(Series.EOARCHEAN_ERATHEM)
}